config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :words

   root 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :word
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player
  has_many   :questions

  validates_presence_of :player
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :games
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :game
  has_many   :answers

  validates_presence_of :game

  def correct_word
    answers.where(is_correct_answer: true).first
  end

  def incorrect_words
    answers.where(is_correct_answer: false).reorder(:word_location)
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  validates :word, presence: true
  validates :definition, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def new
    @word = Word.new
  end

  def show
    @word = Word.find(params[:id])
  end

  def create
    @word = Word.new(word_params)

    if @word.save
      redirect_to @word
    else
      render 'new'
    end
  end

  def index
    @words = Word.all
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      redirect_to @word
    else
      render 'edit'
    end
  end

  def edit
    @word = Word.find(params[:id])
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_path
  end

  private
  def word_params
    params.require(:word).permit(:word, :definition, :part_of_speech)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vocab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to the SAT Vocab Practice</h1>
<%= link_to 'Word List', controller: 'words' %>

app/views/words/edit.html.erb
<h1>Editng Words</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>List of World</h1>
<%= link_to 'New Word', new_word_path %>
<table>
  <p>
  </p>
  <tr>
    <th>Word</th>
    <th>Definition</th>
    <th>Part Of Speech</th>
    <th colspan="3"></th>
  </tr>

  <% @words.each do |word| %>
    <tr>
      <td><%= word.word %></td>
      <td><%= word.definition%></td>
      <td><%= word.part_of_speech%></td>
      <td><%= link_to 'Show', word_path(word) %></td>
      <td><%= link_to 'Edit', edit_word_path(word) %></td>
      <td><%= link_to 'Destroy', word_path(word), 
        method: :delete, data: {confirm: 'Are you sure?'} %> </td>
    </tr>
  <% end %>
</table>

app/views/words/new.html.erb
<h1>New Vocab Word</h1>
<%= render 'form' %>
<%= link_to 'Back', words_path%>

app/views/words/show.html.erb
<h1>List of Vocab Words</h1>
<p>
</p>
<p>
<strong>Word:</strong>
<%= @word.word %>
</p>
<p>
  
</p>
<p>
<strong>Definition:</strong>
<%= @word.definition %>
</p>

<p>
<strong>Part of Speech</strong>
<%= @word.part_of_speech %>
</p>
<%= link_to 'Back', words_path%>
<%= link_to 'Edit', edit_word_path(@word) %>